name: hyphen_browser
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.5.0
  url_launcher: ^6.3.1
  flutter_inappwebview: ^6.1.5
  flutter_inappwebview_ios: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
